import cupy as cp
from collections import deque
import random
import os
import pickle


class UnifiedWorldModel:
    def __init__(self, input_size=63, hidden_size=128):
        # 1. REPRESENTATION: Raw Features -> Hidden State (s)
        self.W_repr = self._init_weights(input_size, hidden_size)

        # 2. DYNAMICS: (State s + Action a) -> (Next State s' + Reward r)
        # We add +1 to hidden_size to account for the action input
        self.W_dyn = self._init_weights(hidden_size + 1, hidden_size + 1)

        # 3. PREDICTION: State s -> (Policy Probs + Value V)
        # Output is 4 (actions) + 1 (scalar value)
        self.W_pred = self._init_weights(hidden_size, 4 + 1)

        self.lr = 1e-4
        self.memory = deque(maxlen=20000)
        self.batch_size = 64

    def _init_weights(self, i, o):
        return cp.random.randn(i, o) * cp.sqrt(2.0 / i)

    def get_initial_state(self, x):
        """Converts raw MultiPaceAgent data into a latent 'market state'."""
        return cp.tanh(cp.asarray(x) @ self.W_repr)

    def simulate_next(self, s, action):
        """The 'Hallucination' engine. Predicts what happens if we take an action."""
        # 1. Force state 's' to be 2D [Batch, Hidden]
        if s.ndim == 1:
            s = s.reshape(1, -1)

        # 2. Ensure action_input is 2D and matches the batch size of 's'
        # action is typically a float or a 1D array from the planner
        action_input = cp.asarray(action).reshape(-1, 1)

        # 3. Concatenate (Now both are guaranteed to be 2D)
        combined = cp.concatenate([s, action_input], axis=1)

        out = cp.tanh(combined @ self.W_dyn)

        # Slice: everything but the last column is the state, last column is reward
        next_s = out[:, :-1]
        predicted_reward = out[:, -1:]

        return next_s, predicted_reward

    def predict(self, s):
        """Evaluates a state for its immediate value and best move."""
        # Force s to be 2D if it's 1D [batch_size, hidden_size]
        if s.ndim == 1:
            s = s.reshape(1, -1)

        out = s @ self.W_pred

        # Slicing out[:, :4] now works because 'out' is guaranteed 2D
        probs = self._softmax(out[:, :4])
        value = out[:, 4:]
        return probs, value

    def _softmax(self, z):
        # Ensure z is 2D for the axis=1 calculation
        if z.ndim == 1:
            z = z.reshape(1, -1)
        z = z - cp.max(z, axis=1, keepdims=True)
        exp = cp.exp(z)
        return exp / cp.sum(exp, axis=1, keepdims=True)

    def record(self, s, a, next_s, r, target_pi):
        """
        s: Raw multi-pace features (current)
        a: Discrete action taken (0, 1, 2, 3)
        next_s: Raw multi-pace features (actual observed next state)
        r: The actual shaped reward received
        target_pi: The probability distribution generated by the MCTS Planner
        """
        self.memory.append((s, a, next_s, r, target_pi))


    def learn_from_memory(self):
        if len(self.memory) < self.batch_size:
            return

        # 1. Sample a batch
        batch = random.sample(self.memory, self.batch_size)
        raw_s, actions, raw_next_s, rewards, target_pis = zip(*batch)

        # Convert to CuPy arrays
        S = cp.array(raw_s, dtype=cp.float32)
        Next_S = cp.array(raw_next_s, dtype=cp.float32)
        A_discrete = cp.array(actions, dtype=cp.int32)
        R = cp.array(rewards, dtype=cp.float32).reshape(-1, 1)
        Pi = cp.array(target_pis, dtype=cp.float32)

        # Convert discrete actions to continuous signals (-1.0 to 1.0) for the Dynamics Net
        mapping = cp.array([1.0, -1.0, 0.0, 0.0], dtype=cp.float32)
        A_continuous = mapping[A_discrete].reshape(-1, 1)

        # ==========================================
        # FORWARD PASS
        # ==========================================
        # Representation
        z_repr = S @ self.W_repr
        s_latent = cp.tanh(z_repr)

        # Target Representation (What the next state actually looked like)
        # We use stop_gradient here by not tracking its derivative
        true_next_latent = cp.tanh(Next_S @ self.W_repr)

        # Prediction
        pred_out = s_latent @ self.W_pred
        pred_logits = pred_out[:, :4]
        pred_value = pred_out[:, 4:]

        pred_probs = self._softmax(pred_logits)

        # Dynamics (Hallucination)
        dyn_input = cp.concatenate([s_latent, A_continuous], axis=1)
        dyn_out = cp.tanh(dyn_input @ self.W_dyn)
        pred_next_latent = dyn_out[:, :-1]
        pred_reward = dyn_out[:, -1:]

        # ==========================================
        # LOSS & GRADIENT CALCULATION (BACKPROP)
        # ==========================================

        # --- A. Prediction Head Gradients ---
        # 1. Policy Loss (Cross Entropy against MCTS Probs)
        dZ_policy = (pred_probs - Pi) / self.batch_size

        # 2. Value Loss (MSE against actual Reward for 1-step)
        dZ_value = (pred_value - R) / self.batch_size

        dZ_pred = cp.concatenate([dZ_policy, dZ_value], axis=1)
        dW_pred = s_latent.T @ dZ_pred
        dS_from_pred = dZ_pred @ self.W_pred.T

        # --- B. Dynamics Head Gradients ---
        # 1. State Prediction Error (MSE: hallucination vs true next state)
        d_next_s = (pred_next_latent - true_next_latent) / self.batch_size

        # 2. Reward Prediction Error (MSE: hallucinated reward vs actual reward)
        d_reward = (pred_reward - R) / self.batch_size

        dZ_dyn_out = cp.concatenate([d_next_s, d_reward], axis=1)
        # Apply Tanh derivative
        dZ_dyn = dZ_dyn_out * (1 - dyn_out ** 2)

        dW_dyn = dyn_input.T @ dZ_dyn
        # Gradient flowing back to the latent state (ignore the action input gradient)
        dS_from_dyn = (dZ_dyn @ self.W_dyn.T)[:, :-1]

        # --- C. Representation Head Gradients ---
        # The latent state is updated by both the Prediction error AND the Dynamics error
        dS_total = dS_from_pred + dS_from_dyn

        # Apply Tanh derivative
        dZ_repr = dS_total * (1 - s_latent ** 2)
        dW_repr = S.T @ dZ_repr

        # ==========================================
        # WEIGHT UPDATE (Gradient Descent)
        # ==========================================
        # We use -= because we are MINIMIZING error, not maximizing reward
        self.W_pred -= self.lr * dW_pred
        self.W_dyn -= self.lr * dW_dyn
        self.W_repr -= self.lr * dW_repr



    def save(self, path="outcomes/best_world_model.pkl"):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        data = {
            "W_repr": cp.asnumpy(self.W_repr),
            "W_dyn": cp.asnumpy(self.W_dyn),
            "W_pred": cp.asnumpy(self.W_pred),
            "input_size": self.W_repr.shape[0]
        }
        with open(path, "wb") as f:
            pickle.dump(data, f)

    def load(self, path="outcomes/best_world_model.pkl"):
        if not os.path.exists(path):
            print("No world model found. Starting with fresh weights.")
            return

        with open(path, "rb") as f:
            data = pickle.load(f)

        # Protection against architecture mismatch
        saved_input_size = data.get("input_size", 0)
        if saved_input_size != self.W_repr.shape[0]:
            print(f"Shape Mismatch: Saved expects {saved_input_size}, Current expects {self.W_repr.shape[0]}.")
            print("Retraining required due to architecture changes.")
            return

        self.W_repr = cp.asarray(data["W_repr"])
        self.W_dyn = cp.asarray(data["W_dyn"])
        self.W_pred = cp.asarray(data["W_pred"])
        print("World Model weights loaded successfully.")